---
- name: Apache
  hosts: all
  become: yes
  
  tasks:
  
  - name: uninstall
    yum: name=httpd state=absent
    
  - name: delete
    file: path='/var/www/html/index.html' state=absent
    
  - name: open port
    firewalld: port=80/tcp permanent=true state=disabled
    
  - name: reloaded
    systemd: name=firewalld state=reloaded