---
- name: Create users
  hosts: all
  become: yes
  vars_files:
    - users.yml
  tasks:
    - name: name, comment, home, password
      user:
        name: "{{ item.name }}"
        comment: "{{ item.name }}@example.com"
        home: "/home/{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      with_items: "{{ users }}"